# Generated by Django 5.0.1 on 2025-05-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField()),
                ('remind_via', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
